### ISSUE TITLE
Being able to set different colors based on the word being drawn

### ISSUE THREAD

**Issue by TDC-mobstation** [knowledgepicker/word-cloud#20]
Hello!
What do you think of the idea of being able to return different results from the Colorizer based on the word being drawn? The use case in mind is that for certain word cloud we'd like to be able to provide a list of words that should be highlighted (eg drawn in another color than the base color).

We've found no way of doing this with how the library looks currently (please correct us if we've missed anything). One idea would perhaps be that the GetColorAsHex would receive the word being drawn and you could handle the return of the color in the Colorizer as you do currently. Any thoughts on this?

**Comment by jjonescz** [comment]
Yes, I think that's a good idea. Should not be difficult to implement, so I can work on it later this week. Or if you want to send a pull request, I will gladly accept it.

Note that an external contributor also previously implemented the colorization in https://github.com/knowledgepicker/word-cloud/pull/4.

**Comment by jjonescz** [comment]
🎉 This has been added in the latest version [1.3.0](https://github.com/knowledgepicker/word-cloud/releases/tag/v1.3.0) (available on [NuGet](https://www.nuget.org/packages/KnowledgePicker.WordCloud/1.3.0)).

Thanks for the idea. Hope this helps for your use case. If not, please let me know.

**Comment by TDC-mobstation** [comment]
That works excellent, what a nice Christmas gift !🥳 

Thanks a lot for this =)
