### ISSUE TITLE
Item Color

### ISSUE THREAD

**Issue by ExtremeSRL** [knowledgepicker/word-cloud#23]
Hi,
in the example:
<svg viewBox="0,0,@wordCloud.Width,@wordCloud.Height">
@foreach (var (item, fontSize) in items)
{
    const string format = "0.##"; // Use at most 2 decimal places.
    var x = (item.Location.X - item.Measured.Left).ToString(format);
    var y = (item.Location.Y - item.Measured.Top).ToString(format);
    var fs = fontSize.ToString(format);
    <text transform="translate(@x, @y)" font-size="@fs">@item.Entry.Word</text>
}
</svg>

**How can I in the loop get the color of the item.
thank you!**

**Comment by jjonescz** [comment]
Hi, thanks for the question, I agree it's not very straightforward. Currently you can get color only though colorizer. So, assuming you have the colorizer you pass to `WordCloudGenerator` stored in a field:

```cs
IColorizer colorizer = new RandomColorizer();
```

you can use it to access the current item's color:

```razor
@foreach (var (item, fontSize) in items)
{
    const string format = "0.##"; // Use at most 2 decimal places.
    var x = (item.Location.X - item.Measured.Left).ToString(format);
    var y = (item.Location.Y - item.Measured.Top).ToString(format);
    var fs = fontSize.ToString(format);
    var color = colorizer.GetColor(item) ?? Color.Black; // 👈 here
    var hex = $"#{color.R:X2}{color.G:X2}{color.B:X2}";
    <text transform="translate(@x, @y)" font-size="@fs" fill="@hex">@item.Entry.Word</text>
}
```

Note that `colorizer.GetColor` returns `null` if the colorizer doesn't return a color (`RandomColorizer` always returns a color, but `SpecificColorizer` without a fallback might not).

**Comment by jjonescz** [comment]
I will add an utility method on `WordCloudGenerator`, so this becomes simpler:

```razor
@foreach (var (item, fontSize) in items)
{
    const string format = "0.##"; // Use at most 2 decimal places.
    var x = (item.Location.X - item.Measured.Left).ToString(format);
    var y = (item.Location.Y - item.Measured.Top).ToString(format);
    var fs = fontSize.ToString(format);
    var color = wcg.GetColorHexString(item); // 👈 here
    <text transform="translate(@x, @y)" font-size="@fs" fill="@color">@item.Entry.Word</text>
}
```
