### ISSUE TITLE
Missing Font Settings

### ISSUE THREAD

**Issue by inan-echs** [knowledgepicker/word-cloud#37]
there seems to be no way to customize the font used to make the word cloud

**Comment by jjonescz** [comment]
You can specify font when creating an instance of `SkGraphicEngine`, an example can be seen in the tests here:

https://github.com/knowledgepicker/word-cloud/blob/9aac80b960fbd146b5c64543afe227490f862887/test/KnowledgePicker.WordCloud.Tests/IntegrationTests.cs#L153
